require('mappings')
require("options")
require("plugins/packer/config")
--require("plugins.status.statusbar")
require("plugins/lsp/trouble")
--require("plugins/other/comment")
require("plugins/comp/init")
require("plugins/lsp/config")
require("plugins/tree/telescope")
require("plugins/other/color")
require("plugins/other/treesitter")
require("plugins/tree/tree")
require("plugins/git/git")
require("plugins/other/tmux")
--require("plugins/other/transparent")
require("plugins/other/nvim-ts-autotag")

